server {
    listen [::]:80;
    listen 80;

    default_type text/html;

    location / {
        return 200 '<html><body>
<h2>Polaris Lab - Upstream Web Server</h2>
<p>Server address : $server_addr</p>
<p>Client address : $remote_addr</p>
<p>via Router     : check <code>traceroute6 fd10::100</code> from your host</p>
</body></html>\n';
    }
}
