// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of go-ra

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/gora/v1/gora.proto

package gorav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoRAService_GetStatus_FullMethodName       = "/gora.v1.GoRAService/GetStatus"
	GoRAService_ListInterfaces_FullMethodName  = "/gora.v1.GoRAService/ListInterfaces"
	GoRAService_AddInterface_FullMethodName    = "/gora.v1.GoRAService/AddInterface"
	GoRAService_UpdateInterface_FullMethodName = "/gora.v1.GoRAService/UpdateInterface"
	GoRAService_DeleteInterface_FullMethodName = "/gora.v1.GoRAService/DeleteInterface"
)

// GoRAServiceClient is the client API for GoRAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoRAServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	AddInterface(ctx context.Context, in *AddInterfaceRequest, opts ...grpc.CallOption) (*AddInterfaceResponse, error)
	UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc.CallOption) (*UpdateInterfaceResponse, error)
	DeleteInterface(ctx context.Context, in *DeleteInterfaceRequest, opts ...grpc.CallOption) (*DeleteInterfaceResponse, error)
}

type goRAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoRAServiceClient(cc grpc.ClientConnInterface) GoRAServiceClient {
	return &goRAServiceClient{cc}
}

func (c *goRAServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, GoRAService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goRAServiceClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, GoRAService_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goRAServiceClient) AddInterface(ctx context.Context, in *AddInterfaceRequest, opts ...grpc.CallOption) (*AddInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddInterfaceResponse)
	err := c.cc.Invoke(ctx, GoRAService_AddInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goRAServiceClient) UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc.CallOption) (*UpdateInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInterfaceResponse)
	err := c.cc.Invoke(ctx, GoRAService_UpdateInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goRAServiceClient) DeleteInterface(ctx context.Context, in *DeleteInterfaceRequest, opts ...grpc.CallOption) (*DeleteInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInterfaceResponse)
	err := c.cc.Invoke(ctx, GoRAService_DeleteInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoRAServiceServer is the server API for GoRAService service.
// All implementations must embed UnimplementedGoRAServiceServer
// for forward compatibility.
type GoRAServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	AddInterface(context.Context, *AddInterfaceRequest) (*AddInterfaceResponse, error)
	UpdateInterface(context.Context, *UpdateInterfaceRequest) (*UpdateInterfaceResponse, error)
	DeleteInterface(context.Context, *DeleteInterfaceRequest) (*DeleteInterfaceResponse, error)
	mustEmbedUnimplementedGoRAServiceServer()
}

// UnimplementedGoRAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoRAServiceServer struct{}

func (UnimplementedGoRAServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedGoRAServiceServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedGoRAServiceServer) AddInterface(context.Context, *AddInterfaceRequest) (*AddInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddInterface not implemented")
}
func (UnimplementedGoRAServiceServer) UpdateInterface(context.Context, *UpdateInterfaceRequest) (*UpdateInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInterface not implemented")
}
func (UnimplementedGoRAServiceServer) DeleteInterface(context.Context, *DeleteInterfaceRequest) (*DeleteInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInterface not implemented")
}
func (UnimplementedGoRAServiceServer) mustEmbedUnimplementedGoRAServiceServer() {}
func (UnimplementedGoRAServiceServer) testEmbeddedByValue()                     {}

// UnsafeGoRAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoRAServiceServer will
// result in compilation errors.
type UnsafeGoRAServiceServer interface {
	mustEmbedUnimplementedGoRAServiceServer()
}

func RegisterGoRAServiceServer(s grpc.ServiceRegistrar, srv GoRAServiceServer) {
	// If the following call panics, it indicates UnimplementedGoRAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoRAService_ServiceDesc, srv)
}

func _GoRAService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRAServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoRAService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRAServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoRAService_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRAServiceServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoRAService_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRAServiceServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoRAService_AddInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRAServiceServer).AddInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoRAService_AddInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRAServiceServer).AddInterface(ctx, req.(*AddInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoRAService_UpdateInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRAServiceServer).UpdateInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoRAService_UpdateInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRAServiceServer).UpdateInterface(ctx, req.(*UpdateInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoRAService_DeleteInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRAServiceServer).DeleteInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoRAService_DeleteInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRAServiceServer).DeleteInterface(ctx, req.(*DeleteInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoRAService_ServiceDesc is the grpc.ServiceDesc for GoRAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoRAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gora.v1.GoRAService",
	HandlerType: (*GoRAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _GoRAService_GetStatus_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _GoRAService_ListInterfaces_Handler,
		},
		{
			MethodName: "AddInterface",
			Handler:    _GoRAService_AddInterface_Handler,
		},
		{
			MethodName: "UpdateInterface",
			Handler:    _GoRAService_UpdateInterface_Handler,
		},
		{
			MethodName: "DeleteInterface",
			Handler:    _GoRAService_DeleteInterface_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/gora/v1/gora.proto",
}
