// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of go-ra

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/gora/v1/gora.proto

package gorav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*InterfaceStatus     `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetInterfaces() []*InterfaceStatus {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type InterfaceStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastUpdate      int64                  `protobuf:"varint,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	TxSolicitedRa   int32                  `protobuf:"varint,6,opt,name=tx_solicited_ra,json=txSolicitedRa,proto3" json:"tx_solicited_ra,omitempty"`
	TxUnsolicitedRa int32                  `protobuf:"varint,7,opt,name=tx_unsolicited_ra,json=txUnsolicitedRa,proto3" json:"tx_unsolicited_ra,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterfaceStatus) Reset() {
	*x = InterfaceStatus{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStatus) ProtoMessage() {}

func (x *InterfaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStatus.ProtoReflect.Descriptor instead.
func (*InterfaceStatus) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterfaceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InterfaceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InterfaceStatus) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *InterfaceStatus) GetTxSolicitedRa() int32 {
	if x != nil {
		return x.TxSolicitedRa
	}
	return 0
}

func (x *InterfaceStatus) GetTxUnsolicitedRa() int32 {
	if x != nil {
		return x.TxUnsolicitedRa
	}
	return 0
}

type ListInterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequest) Reset() {
	*x = ListInterfacesRequest{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequest) ProtoMessage() {}

func (x *ListInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesRequest.ProtoReflect.Descriptor instead.
func (*ListInterfacesRequest) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{3}
}

type ListInterfacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*InterfaceConfig     `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesResponse) Reset() {
	*x = ListInterfacesResponse{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesResponse) ProtoMessage() {}

func (x *ListInterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesResponse.ProtoReflect.Descriptor instead.
func (*ListInterfacesResponse) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{4}
}

func (x *ListInterfacesResponse) GetInterfaces() []*InterfaceConfig {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type AddInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     *InterfaceConfig       `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInterfaceRequest) Reset() {
	*x = AddInterfaceRequest{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInterfaceRequest) ProtoMessage() {}

func (x *AddInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInterfaceRequest.ProtoReflect.Descriptor instead.
func (*AddInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{5}
}

func (x *AddInterfaceRequest) GetInterface() *InterfaceConfig {
	if x != nil {
		return x.Interface
	}
	return nil
}

type AddInterfaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInterfaceResponse) Reset() {
	*x = AddInterfaceResponse{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInterfaceResponse) ProtoMessage() {}

func (x *AddInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInterfaceResponse.ProtoReflect.Descriptor instead.
func (*AddInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{6}
}

type UpdateInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     *InterfaceConfig       `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInterfaceRequest) Reset() {
	*x = UpdateInterfaceRequest{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterfaceRequest) ProtoMessage() {}

func (x *UpdateInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterfaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInterfaceRequest) GetInterface() *InterfaceConfig {
	if x != nil {
		return x.Interface
	}
	return nil
}

type UpdateInterfaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInterfaceResponse) Reset() {
	*x = UpdateInterfaceResponse{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterfaceResponse) ProtoMessage() {}

func (x *UpdateInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterfaceResponse.ProtoReflect.Descriptor instead.
func (*UpdateInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{8}
}

type DeleteInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInterfaceRequest) Reset() {
	*x = DeleteInterfaceRequest{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInterfaceRequest) ProtoMessage() {}

func (x *DeleteInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInterfaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInterfaceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteInterfaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInterfaceResponse) Reset() {
	*x = DeleteInterfaceResponse{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInterfaceResponse) ProtoMessage() {}

func (x *DeleteInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInterfaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{10}
}

type InterfaceConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description                string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name                       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RaIntervalMilliseconds     int32                  `protobuf:"varint,4,opt,name=ra_interval_milliseconds,json=raIntervalMilliseconds,proto3" json:"ra_interval_milliseconds,omitempty"`
	CurrentHopLimit            int32                  `protobuf:"varint,5,opt,name=current_hop_limit,json=currentHopLimit,proto3" json:"current_hop_limit,omitempty"`
	Managed                    bool                   `protobuf:"varint,6,opt,name=managed,proto3" json:"managed,omitempty"`
	Other                      bool                   `protobuf:"varint,7,opt,name=other,proto3" json:"other,omitempty"`
	Preference                 string                 `protobuf:"bytes,8,opt,name=preference,proto3" json:"preference,omitempty"`
	RouterLifetimeSeconds      int32                  `protobuf:"varint,9,opt,name=router_lifetime_seconds,json=routerLifetimeSeconds,proto3" json:"router_lifetime_seconds,omitempty"`
	ReachableTimeMilliseconds  int64                  `protobuf:"varint,10,opt,name=reachable_time_milliseconds,json=reachableTimeMilliseconds,proto3" json:"reachable_time_milliseconds,omitempty"`
	RetransmitTimeMilliseconds int64                  `protobuf:"varint,11,opt,name=retransmit_time_milliseconds,json=retransmitTimeMilliseconds,proto3" json:"retransmit_time_milliseconds,omitempty"`
	Mtu                        int64                  `protobuf:"varint,12,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Prefixes                   []*PrefixConfig        `protobuf:"bytes,13,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	Routes                     []*RouteConfig         `protobuf:"bytes,14,rep,name=routes,proto3" json:"routes,omitempty"`
	Rdnsses                    []*RdnssConfig         `protobuf:"bytes,15,rep,name=rdnsses,proto3" json:"rdnsses,omitempty"`
	Dnssls                     []*DnsslConfig         `protobuf:"bytes,16,rep,name=dnssls,proto3" json:"dnssls,omitempty"`
	Nat64Prefixes              []*Nat64PrefixConfig   `protobuf:"bytes,17,rep,name=nat64_prefixes,json=nat64Prefixes,proto3" json:"nat64_prefixes,omitempty"`
	Clients                    []string               `protobuf:"bytes,18,rep,name=clients,proto3" json:"clients,omitempty"`
	SendGoodbye                *wrapperspb.BoolValue  `protobuf:"bytes,19,opt,name=send_goodbye,json=sendGoodbye,proto3" json:"send_goodbye,omitempty"`
	DisableRsReply             bool                   `protobuf:"varint,20,opt,name=disable_rs_reply,json=disableRsReply,proto3" json:"disable_rs_reply,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *InterfaceConfig) Reset() {
	*x = InterfaceConfig{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceConfig) ProtoMessage() {}

func (x *InterfaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceConfig.ProtoReflect.Descriptor instead.
func (*InterfaceConfig) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{11}
}

func (x *InterfaceConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterfaceConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InterfaceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceConfig) GetRaIntervalMilliseconds() int32 {
	if x != nil {
		return x.RaIntervalMilliseconds
	}
	return 0
}

func (x *InterfaceConfig) GetCurrentHopLimit() int32 {
	if x != nil {
		return x.CurrentHopLimit
	}
	return 0
}

func (x *InterfaceConfig) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *InterfaceConfig) GetOther() bool {
	if x != nil {
		return x.Other
	}
	return false
}

func (x *InterfaceConfig) GetPreference() string {
	if x != nil {
		return x.Preference
	}
	return ""
}

func (x *InterfaceConfig) GetRouterLifetimeSeconds() int32 {
	if x != nil {
		return x.RouterLifetimeSeconds
	}
	return 0
}

func (x *InterfaceConfig) GetReachableTimeMilliseconds() int64 {
	if x != nil {
		return x.ReachableTimeMilliseconds
	}
	return 0
}

func (x *InterfaceConfig) GetRetransmitTimeMilliseconds() int64 {
	if x != nil {
		return x.RetransmitTimeMilliseconds
	}
	return 0
}

func (x *InterfaceConfig) GetMtu() int64 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *InterfaceConfig) GetPrefixes() []*PrefixConfig {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *InterfaceConfig) GetRoutes() []*RouteConfig {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *InterfaceConfig) GetRdnsses() []*RdnssConfig {
	if x != nil {
		return x.Rdnsses
	}
	return nil
}

func (x *InterfaceConfig) GetDnssls() []*DnsslConfig {
	if x != nil {
		return x.Dnssls
	}
	return nil
}

func (x *InterfaceConfig) GetNat64Prefixes() []*Nat64PrefixConfig {
	if x != nil {
		return x.Nat64Prefixes
	}
	return nil
}

func (x *InterfaceConfig) GetClients() []string {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *InterfaceConfig) GetSendGoodbye() *wrapperspb.BoolValue {
	if x != nil {
		return x.SendGoodbye
	}
	return nil
}

func (x *InterfaceConfig) GetDisableRsReply() bool {
	if x != nil {
		return x.DisableRsReply
	}
	return false
}

type PrefixConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Prefix                   string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	OnLink                   bool                   `protobuf:"varint,2,opt,name=on_link,json=onLink,proto3" json:"on_link,omitempty"`
	Autonomous               bool                   `protobuf:"varint,3,opt,name=autonomous,proto3" json:"autonomous,omitempty"`
	ValidLifetimeSeconds     *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=valid_lifetime_seconds,json=validLifetimeSeconds,proto3" json:"valid_lifetime_seconds,omitempty"`
	PreferredLifetimeSeconds *wrapperspb.Int64Value `protobuf:"bytes,5,opt,name=preferred_lifetime_seconds,json=preferredLifetimeSeconds,proto3" json:"preferred_lifetime_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PrefixConfig) Reset() {
	*x = PrefixConfig{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixConfig) ProtoMessage() {}

func (x *PrefixConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixConfig.ProtoReflect.Descriptor instead.
func (*PrefixConfig) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{12}
}

func (x *PrefixConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixConfig) GetOnLink() bool {
	if x != nil {
		return x.OnLink
	}
	return false
}

func (x *PrefixConfig) GetAutonomous() bool {
	if x != nil {
		return x.Autonomous
	}
	return false
}

func (x *PrefixConfig) GetValidLifetimeSeconds() *wrapperspb.Int64Value {
	if x != nil {
		return x.ValidLifetimeSeconds
	}
	return nil
}

func (x *PrefixConfig) GetPreferredLifetimeSeconds() *wrapperspb.Int64Value {
	if x != nil {
		return x.PreferredLifetimeSeconds
	}
	return nil
}

type RouteConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prefix          string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	LifetimeSeconds int64                  `protobuf:"varint,2,opt,name=lifetime_seconds,json=lifetimeSeconds,proto3" json:"lifetime_seconds,omitempty"`
	Preference      string                 `protobuf:"bytes,3,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{13}
}

func (x *RouteConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *RouteConfig) GetLifetimeSeconds() int64 {
	if x != nil {
		return x.LifetimeSeconds
	}
	return 0
}

func (x *RouteConfig) GetPreference() string {
	if x != nil {
		return x.Preference
	}
	return ""
}

type RdnssConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LifetimeSeconds int64                  `protobuf:"varint,1,opt,name=lifetime_seconds,json=lifetimeSeconds,proto3" json:"lifetime_seconds,omitempty"`
	Addresses       []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RdnssConfig) Reset() {
	*x = RdnssConfig{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RdnssConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RdnssConfig) ProtoMessage() {}

func (x *RdnssConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RdnssConfig.ProtoReflect.Descriptor instead.
func (*RdnssConfig) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{14}
}

func (x *RdnssConfig) GetLifetimeSeconds() int64 {
	if x != nil {
		return x.LifetimeSeconds
	}
	return 0
}

func (x *RdnssConfig) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type DnsslConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LifetimeSeconds int64                  `protobuf:"varint,1,opt,name=lifetime_seconds,json=lifetimeSeconds,proto3" json:"lifetime_seconds,omitempty"`
	DomainNames     []string               `protobuf:"bytes,2,rep,name=domain_names,json=domainNames,proto3" json:"domain_names,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DnsslConfig) Reset() {
	*x = DnsslConfig{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsslConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsslConfig) ProtoMessage() {}

func (x *DnsslConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsslConfig.ProtoReflect.Descriptor instead.
func (*DnsslConfig) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{15}
}

func (x *DnsslConfig) GetLifetimeSeconds() int64 {
	if x != nil {
		return x.LifetimeSeconds
	}
	return 0
}

func (x *DnsslConfig) GetDomainNames() []string {
	if x != nil {
		return x.DomainNames
	}
	return nil
}

type Nat64PrefixConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prefix          string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	LifetimeSeconds *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=lifetime_seconds,json=lifetimeSeconds,proto3" json:"lifetime_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Nat64PrefixConfig) Reset() {
	*x = Nat64PrefixConfig{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nat64PrefixConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nat64PrefixConfig) ProtoMessage() {}

func (x *Nat64PrefixConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nat64PrefixConfig.ProtoReflect.Descriptor instead.
func (*Nat64PrefixConfig) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{16}
}

func (x *Nat64PrefixConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Nat64PrefixConfig) GetLifetimeSeconds() *wrapperspb.Int64Value {
	if x != nil {
		return x.LifetimeSeconds
	}
	return nil
}

var File_api_gora_v1_gora_proto protoreflect.FileDescriptor

const file_api_gora_v1_gora_proto_rawDesc = "" +
	"\n" +
	"\x16api/gora/v1/gora.proto\x12\agora.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x12\n" +
	"\x10GetStatusRequest\"M\n" +
	"\x11GetStatusResponse\x128\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x18.gora.v1.InterfaceStatusR\n" +
	"interfaces\"\xda\x01\n" +
	"\x0fInterfaceStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vlast_update\x18\x05 \x01(\x03R\n" +
	"lastUpdate\x12&\n" +
	"\x0ftx_solicited_ra\x18\x06 \x01(\x05R\rtxSolicitedRa\x12*\n" +
	"\x11tx_unsolicited_ra\x18\a \x01(\x05R\x0ftxUnsolicitedRa\"\x17\n" +
	"\x15ListInterfacesRequest\"R\n" +
	"\x16ListInterfacesResponse\x128\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x18.gora.v1.InterfaceConfigR\n" +
	"interfaces\"M\n" +
	"\x13AddInterfaceRequest\x126\n" +
	"\tinterface\x18\x01 \x01(\v2\x18.gora.v1.InterfaceConfigR\tinterface\"\x16\n" +
	"\x14AddInterfaceResponse\"P\n" +
	"\x16UpdateInterfaceRequest\x126\n" +
	"\tinterface\x18\x01 \x01(\v2\x18.gora.v1.InterfaceConfigR\tinterface\"\x19\n" +
	"\x17UpdateInterfaceResponse\"(\n" +
	"\x16DeleteInterfaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x19\n" +
	"\x17DeleteInterfaceResponse\"\xde\x06\n" +
	"\x0fInterfaceConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x128\n" +
	"\x18ra_interval_milliseconds\x18\x04 \x01(\x05R\x16raIntervalMilliseconds\x12*\n" +
	"\x11current_hop_limit\x18\x05 \x01(\x05R\x0fcurrentHopLimit\x12\x18\n" +
	"\amanaged\x18\x06 \x01(\bR\amanaged\x12\x14\n" +
	"\x05other\x18\a \x01(\bR\x05other\x12\x1e\n" +
	"\n" +
	"preference\x18\b \x01(\tR\n" +
	"preference\x126\n" +
	"\x17router_lifetime_seconds\x18\t \x01(\x05R\x15routerLifetimeSeconds\x12>\n" +
	"\x1breachable_time_milliseconds\x18\n" +
	" \x01(\x03R\x19reachableTimeMilliseconds\x12@\n" +
	"\x1cretransmit_time_milliseconds\x18\v \x01(\x03R\x1aretransmitTimeMilliseconds\x12\x10\n" +
	"\x03mtu\x18\f \x01(\x03R\x03mtu\x121\n" +
	"\bprefixes\x18\r \x03(\v2\x15.gora.v1.PrefixConfigR\bprefixes\x12,\n" +
	"\x06routes\x18\x0e \x03(\v2\x14.gora.v1.RouteConfigR\x06routes\x12.\n" +
	"\ardnsses\x18\x0f \x03(\v2\x14.gora.v1.RdnssConfigR\ardnsses\x12,\n" +
	"\x06dnssls\x18\x10 \x03(\v2\x14.gora.v1.DnsslConfigR\x06dnssls\x12A\n" +
	"\x0enat64_prefixes\x18\x11 \x03(\v2\x1a.gora.v1.Nat64PrefixConfigR\rnat64Prefixes\x12\x18\n" +
	"\aclients\x18\x12 \x03(\tR\aclients\x12=\n" +
	"\fsend_goodbye\x18\x13 \x01(\v2\x1a.google.protobuf.BoolValueR\vsendGoodbye\x12(\n" +
	"\x10disable_rs_reply\x18\x14 \x01(\bR\x0edisableRsReply\"\x8d\x02\n" +
	"\fPrefixConfig\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x17\n" +
	"\aon_link\x18\x02 \x01(\bR\x06onLink\x12\x1e\n" +
	"\n" +
	"autonomous\x18\x03 \x01(\bR\n" +
	"autonomous\x12Q\n" +
	"\x16valid_lifetime_seconds\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x14validLifetimeSeconds\x12Y\n" +
	"\x1apreferred_lifetime_seconds\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\x18preferredLifetimeSeconds\"p\n" +
	"\vRouteConfig\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12)\n" +
	"\x10lifetime_seconds\x18\x02 \x01(\x03R\x0flifetimeSeconds\x12\x1e\n" +
	"\n" +
	"preference\x18\x03 \x01(\tR\n" +
	"preference\"V\n" +
	"\vRdnssConfig\x12)\n" +
	"\x10lifetime_seconds\x18\x01 \x01(\x03R\x0flifetimeSeconds\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\"[\n" +
	"\vDnsslConfig\x12)\n" +
	"\x10lifetime_seconds\x18\x01 \x01(\x03R\x0flifetimeSeconds\x12!\n" +
	"\fdomain_names\x18\x02 \x03(\tR\vdomainNames\"s\n" +
	"\x11Nat64PrefixConfig\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12F\n" +
	"\x10lifetime_seconds\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x0flifetimeSeconds2\x9d\x03\n" +
	"\vGoRAService\x12B\n" +
	"\tGetStatus\x12\x19.gora.v1.GetStatusRequest\x1a\x1a.gora.v1.GetStatusResponse\x12Q\n" +
	"\x0eListInterfaces\x12\x1e.gora.v1.ListInterfacesRequest\x1a\x1f.gora.v1.ListInterfacesResponse\x12K\n" +
	"\fAddInterface\x12\x1c.gora.v1.AddInterfaceRequest\x1a\x1d.gora.v1.AddInterfaceResponse\x12T\n" +
	"\x0fUpdateInterface\x12\x1f.gora.v1.UpdateInterfaceRequest\x1a .gora.v1.UpdateInterfaceResponse\x12T\n" +
	"\x0fDeleteInterface\x12\x1f.gora.v1.DeleteInterfaceRequest\x1a .gora.v1.DeleteInterfaceResponseB4Z2github.com/YutaroHayakawa/go-ra/api/gora/v1;gorav1b\x06proto3"

var (
	file_api_gora_v1_gora_proto_rawDescOnce sync.Once
	file_api_gora_v1_gora_proto_rawDescData []byte
)

func file_api_gora_v1_gora_proto_rawDescGZIP() []byte {
	file_api_gora_v1_gora_proto_rawDescOnce.Do(func() {
		file_api_gora_v1_gora_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gora_v1_gora_proto_rawDesc), len(file_api_gora_v1_gora_proto_rawDesc)))
	})
	return file_api_gora_v1_gora_proto_rawDescData
}

var file_api_gora_v1_gora_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_gora_v1_gora_proto_goTypes = []any{
	(*GetStatusRequest)(nil),        // 0: gora.v1.GetStatusRequest
	(*GetStatusResponse)(nil),       // 1: gora.v1.GetStatusResponse
	(*InterfaceStatus)(nil),         // 2: gora.v1.InterfaceStatus
	(*ListInterfacesRequest)(nil),   // 3: gora.v1.ListInterfacesRequest
	(*ListInterfacesResponse)(nil),  // 4: gora.v1.ListInterfacesResponse
	(*AddInterfaceRequest)(nil),     // 5: gora.v1.AddInterfaceRequest
	(*AddInterfaceResponse)(nil),    // 6: gora.v1.AddInterfaceResponse
	(*UpdateInterfaceRequest)(nil),  // 7: gora.v1.UpdateInterfaceRequest
	(*UpdateInterfaceResponse)(nil), // 8: gora.v1.UpdateInterfaceResponse
	(*DeleteInterfaceRequest)(nil),  // 9: gora.v1.DeleteInterfaceRequest
	(*DeleteInterfaceResponse)(nil), // 10: gora.v1.DeleteInterfaceResponse
	(*InterfaceConfig)(nil),         // 11: gora.v1.InterfaceConfig
	(*PrefixConfig)(nil),            // 12: gora.v1.PrefixConfig
	(*RouteConfig)(nil),             // 13: gora.v1.RouteConfig
	(*RdnssConfig)(nil),             // 14: gora.v1.RdnssConfig
	(*DnsslConfig)(nil),             // 15: gora.v1.DnsslConfig
	(*Nat64PrefixConfig)(nil),       // 16: gora.v1.Nat64PrefixConfig
	(*wrapperspb.BoolValue)(nil),    // 17: google.protobuf.BoolValue
	(*wrapperspb.Int64Value)(nil),   // 18: google.protobuf.Int64Value
}
var file_api_gora_v1_gora_proto_depIdxs = []int32{
	2,  // 0: gora.v1.GetStatusResponse.interfaces:type_name -> gora.v1.InterfaceStatus
	11, // 1: gora.v1.ListInterfacesResponse.interfaces:type_name -> gora.v1.InterfaceConfig
	11, // 2: gora.v1.AddInterfaceRequest.interface:type_name -> gora.v1.InterfaceConfig
	11, // 3: gora.v1.UpdateInterfaceRequest.interface:type_name -> gora.v1.InterfaceConfig
	12, // 4: gora.v1.InterfaceConfig.prefixes:type_name -> gora.v1.PrefixConfig
	13, // 5: gora.v1.InterfaceConfig.routes:type_name -> gora.v1.RouteConfig
	14, // 6: gora.v1.InterfaceConfig.rdnsses:type_name -> gora.v1.RdnssConfig
	15, // 7: gora.v1.InterfaceConfig.dnssls:type_name -> gora.v1.DnsslConfig
	16, // 8: gora.v1.InterfaceConfig.nat64_prefixes:type_name -> gora.v1.Nat64PrefixConfig
	17, // 9: gora.v1.InterfaceConfig.send_goodbye:type_name -> google.protobuf.BoolValue
	18, // 10: gora.v1.PrefixConfig.valid_lifetime_seconds:type_name -> google.protobuf.Int64Value
	18, // 11: gora.v1.PrefixConfig.preferred_lifetime_seconds:type_name -> google.protobuf.Int64Value
	18, // 12: gora.v1.Nat64PrefixConfig.lifetime_seconds:type_name -> google.protobuf.Int64Value
	0,  // 13: gora.v1.GoRAService.GetStatus:input_type -> gora.v1.GetStatusRequest
	3,  // 14: gora.v1.GoRAService.ListInterfaces:input_type -> gora.v1.ListInterfacesRequest
	5,  // 15: gora.v1.GoRAService.AddInterface:input_type -> gora.v1.AddInterfaceRequest
	7,  // 16: gora.v1.GoRAService.UpdateInterface:input_type -> gora.v1.UpdateInterfaceRequest
	9,  // 17: gora.v1.GoRAService.DeleteInterface:input_type -> gora.v1.DeleteInterfaceRequest
	1,  // 18: gora.v1.GoRAService.GetStatus:output_type -> gora.v1.GetStatusResponse
	4,  // 19: gora.v1.GoRAService.ListInterfaces:output_type -> gora.v1.ListInterfacesResponse
	6,  // 20: gora.v1.GoRAService.AddInterface:output_type -> gora.v1.AddInterfaceResponse
	8,  // 21: gora.v1.GoRAService.UpdateInterface:output_type -> gora.v1.UpdateInterfaceResponse
	10, // 22: gora.v1.GoRAService.DeleteInterface:output_type -> gora.v1.DeleteInterfaceResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_gora_v1_gora_proto_init() }
func file_api_gora_v1_gora_proto_init() {
	if File_api_gora_v1_gora_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gora_v1_gora_proto_rawDesc), len(file_api_gora_v1_gora_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gora_v1_gora_proto_goTypes,
		DependencyIndexes: file_api_gora_v1_gora_proto_depIdxs,
		MessageInfos:      file_api_gora_v1_gora_proto_msgTypes,
	}.Build()
	File_api_gora_v1_gora_proto = out.File
	file_api_gora_v1_gora_proto_goTypes = nil
	file_api_gora_v1_gora_proto_depIdxs = nil
}
